### ISSUE TITLE
Cannot find node_modules

### ISSUE THREAD

**Issue by hongkongkiwi** [phumberdroz/openfaas-node12-koa-service#1]
There's a slight logic bug in your current version.

According to your structure it's /app/function with an outside handler in /app/index.js

The problem is that /app/index.js cannot find the node_modules directory which is located in the directory above (e.g. /app/function/node_modules), to fix this we can specify a NODE_MODULES directory via an env variable in the Dockerfile.... e.g.
```
ENV NODE_PATH "${SOURCES}/function/node_modules"
```

This fixes the issue.

**Comment by phumberdroz** [comment]
Hey @hongkongkiwi,

Thanks for reporting this. I created a PR if you could be so kind and verify that this also would work. I would like to avoid setting env vars that users might not expect. 

#2

**Comment by hongkongkiwi** [comment]
Yep, fixes it on my end thanks.
